import React from 'react';
import { type MultipleNutritionResponse, type NutritionData } from '../utils/api';
import { type AlertOptions } from './PremiumAlert';

interface NutritionLabelProps {
  data: NutritionData | MultipleNutritionResponse;
  showAlert: (options: AlertOptions) => void;
}

const NUTRIENT_META: Record<string, { color: string; bg: string }> = {
  'Energy':        { color: '#ea580c', bg: '#fff7ed' },
  'Protein':       { color: '#0284c7', bg: '#f0f9ff' },
  'Total lipid':   { color: '#ca8a04', bg: '#fefce8' },
  'Carbohydrate':  { color: '#16a34a', bg: '#f0fdf4' },
  'Fiber':         { color: '#15803d', bg: '#f0fdf4' },
  'Sugars':        { color: '#db2777', bg: '#fdf2f8' },
  'Fatty acids':   { color: '#b45309', bg: '#fffbeb' },
  'Cholesterol':   { color: '#9333ea', bg: '#faf5ff'},
  'Sodium':        { color: '#0891b2', bg: '#ecfeff' },
  'Calcium':       { color: '#7c3aed', bg: '#faf5ff' },
  'Iron':          { color: '#b91c1c', bg: '#fef2f2' },
  'Potassium':     { color: '#065f46', bg: '#ecfdf5' },
  'Vitamin C':     { color: '#d97706', bg: '#fffbeb' },
  'Vitamin A':     { color: '#c2410c', bg: '#fff7ed' },
};

const getMeta = (name: string) => {
  if (!name) return { color: '#475569', bg: '#f8fafc' };
  for (const [key, val] of Object.entries(NUTRIENT_META)) {
    if (name.includes(key)) return val;
  }
  return { color: '#475569', bg: '#f8fafc' };
};

const formatName = (name: string): string =>
  name
    .replace('Total lipid (fat)', 'Total Fat')
    .replace('Carbohydrate, by difference', 'Carbohydrate')
    .replace('Fiber, total dietary', 'Dietary Fiber')
    .replace('Sugars, total', 'Sugars')
    .replace('Fatty acids, total saturated', 'Saturated Fat')
    .replace('Vitamin C, total ascorbic acid', 'Vitamin C')
    .replace('Vitamin A, RAE', 'Vitamin A')
    .replace(/, total$/, '');

const formatAmount = (amount: number, unit: string): string => {
  const val =
    unit === 'kcal'
      ? Math.round(amount)
      : amount < 1
      ? amount.toFixed(2)
      : amount.toFixed(1);
  return `${val} ${unit === 'kcal' ? 'cal' : unit}`;
};


const NutritionLabel: React.FC<NutritionLabelProps> = ({ data, showAlert }) => {
  const isMultiple =
    'ingredients' in data && Array.isArray((data as MultipleNutritionResponse).ingredients);
  const multiData = isMultiple ? (data as MultipleNutritionResponse) : null;
  const nutrientList = isMultiple
    ? multiData!.total_nutrients ?? []
    : (data as NutritionData).nutrients ?? [];

  const calories = nutrientList.find(n => n.name && n.name.includes('Energy'));

  const getTitle = () => {
    if (!isMultiple) return (data as NutritionData).ingredient || 'Item';
    const names = multiData?.ingredients?.map(ing => ing.ingredient) || [];
    if (names.length === 0) return 'Recipe Totals';
    if (names.length === 1) return names[0];
    if (names.length === 2) return `${names[0]} & ${names[1]}`;
    if (names.length === 3) return `${names[0]}, ${names[1]} & ${names[2]}`;
    return `${names[0]}, ${names[1]} & ${names.length - 2} more`;
  };

  const copyToClipboard = () => {
    const header = isMultiple ? `Recipe Profile (Per 100g)` : `Nutrition Facts: ${(data as NutritionData).ingredient || 'Item'}`;
    const weight = isMultiple ? `Total Weight: ${multiData?.total_weight_g}g` : `Serving Size: ${(data as NutritionData).quantity_g}g`;
    const lines = nutrientList.map(n => `${n.name}: ${n.amount}${n.unit}`);
    const text = `${header}\n${weight}\n\n${lines.join('\n')}\n\nGenerated by Nutritional Label Generator`;

    navigator.clipboard.writeText(text).then(() => {
      showAlert({ type: 'success', message: 'Nutritional facts copied to clipboard!' });
    }).catch(err => {
      console.error('Failed to copy text: ', err);
      showAlert({ type: 'error', message: 'Failed to copy to clipboard.' });
    });
  };

  const visibleNutrients = nutrientList.filter(n => n.name && !n.name.includes('Energy'));

  return (
    <div style={{ width: '100%', boxSizing: 'border-box' }}>

      {/* ── Top header bar ── */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '24px',
        gap: '12px',
      }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
            <div style={{ width: '3px', height: '14px', background: '#10b981', borderRadius: '4px' }} />
            <p style={{
              margin: 0, fontSize: '11px', fontWeight: '800',
              color: '#64748b', letterSpacing: '0.08em', textTransform: 'uppercase',
            }}>
              {isMultiple ? 'Recipe Analysis' : 'Food Analysis'}
            </p>
          </div>
          <h2 style={{ 
            margin: '0 0 6px', 
            fontSize: '28px', 
            fontWeight: '800', 
            color: '#0f172a',
            textTransform: 'capitalize',
            letterSpacing: '-0.02em',
            lineHeight: 1.2
          }}>
            {getTitle()}
          </h2>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{
              fontSize: '11px',
              fontWeight: '800',
              color: '#059669',
              textTransform: 'uppercase',
              letterSpacing: '0.04em',
              background: '#ecfdf5',
              padding: '3px 10px',
              borderRadius: '7px',
              border: '1px solid #d1fae5'
            }}>
              Nutrition Facts
            </span>
            <span style={{ fontSize: '13px', fontWeight: '600', color: '#94a3b8' }}>
              • {isMultiple ? 'Normalized per 100g' : `${(data as NutritionData).quantity_g}g serving`}
            </span>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }}>
          {isMultiple && (
            <div style={{
              background: '#f0fdf4', color: '#16a34a',
              padding: '5px 10px', borderRadius: '10px',
              fontSize: '10px', fontWeight: '800',
              border: '1px solid #dcfce7', whiteSpace: 'nowrap',
              letterSpacing: '0.04em',
            }}>
              ⚖️ WEIGHTED
            </div>
          )}
          <button
            onClick={copyToClipboard}
            style={{
              padding: '8px 14px', borderRadius: '12px',
              background: '#f8fafc', border: '1px solid #e2e8f0',
              cursor: 'pointer', fontSize: '12px', fontWeight: '700',
              color: '#64748b', transition: 'all 0.2s',
              display: 'flex', alignItems: 'center', gap: '5px',
              whiteSpace: 'nowrap',
            }}
            onMouseEnter={e => {
              e.currentTarget.style.background = '#f0fdfa';
              e.currentTarget.style.borderColor = '#ccfbf1';
              e.currentTarget.style.color = '#0d9488';
            }}
            onMouseLeave={e => {
              e.currentTarget.style.background = '#f8fafc';
              e.currentTarget.style.borderColor = '#e2e8f0';
              e.currentTarget.style.color = '#64748b';
            }}
          >
            📋 Copy
          </button>
        </div>
      </div>

      {/* ── Calories hero block ── */}
      {calories && (
        <div style={{
          background: 'white',
          border: '1px solid #e2e8f0',
          borderRadius: '24px',
          padding: '24px 28px',
          marginBottom: '32px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          boxShadow: '0 4px 20px -5px rgba(0,0,0,0.05)',
        }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <span style={{ fontSize: '18px' }}>🔥</span>
              <p style={{ margin: 0, fontSize: '13px', fontWeight: '800', color: '#0f172a', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
                Energy Content
              </p>
            </div>
            <p style={{ margin: 0, fontSize: '14px', color: '#64748b', fontWeight: '500' }}>
              Estimated {isMultiple ? 'per 100g' : 'per serving'}
            </p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{ margin: 0, fontSize: '52px', fontWeight: '800', color: '#0f172a', lineHeight: 1, letterSpacing: '-0.02em' }}>
              {Math.round(calories.amount)}
            </p>
            <p style={{ margin: 0, fontSize: '12px', fontWeight: '700', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.08em', marginTop: '4px' }}>
              Calories
            </p>
          </div>
        </div>
      )}

      {/* ── Nutrient list ── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
        {/* Column headers */}
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          padding: '0 4px 10px',
          borderBottom: '2px solid #f1f5f9',
          marginBottom: '6px',
        }}>
          <span style={{ fontSize: '11px', fontWeight: '800', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
            Nutrient
          </span>
          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            <span style={{ fontSize: '11px', fontWeight: '800', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.08em', minWidth: '80px', textAlign: 'right' }}>
              Amount
            </span>
          </div>
        </div>

        {visibleNutrients.map((nutrient, index) => {
          const meta = getMeta(nutrient.name);
          
          return (
            <div
              key={index}
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                padding: '14px 20px',
                border: '1px solid #f1f5f9',
                borderRadius: '16px',
                backgroundColor: '#ffffff',
                marginBottom: '10px',
                transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
                boxShadow: '0 2px 8px -2px rgba(15,23,42,0.04)',
              }}
              onMouseEnter={e => {
                e.currentTarget.style.borderColor = '#e2e8f0';
                e.currentTarget.style.transform = 'translateY(-1.5px)';
                e.currentTarget.style.boxShadow = '0 12px 20px -8px rgba(15,23,42,0.08)';
              }}
              onMouseLeave={e => {
                e.currentTarget.style.borderColor = '#f1f5f9';
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '0 2px 8px -2px rgba(15,23,42,0.04)';
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <div style={{ 
                  width: '8px', height: '8px', borderRadius: '50%', 
                  background: meta.color, opacity: 0.8,
                  boxShadow: `0 0 10px ${meta.color}40`
                }} />
                <span style={{ fontSize: '15px', fontWeight: '600', color: '#334155', letterSpacing: '-0.01em' }}>
                  {formatName(nutrient.name)}
                </span>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{
                  fontSize: '15px', fontWeight: '700', color: '#1e293b',
                  minWidth: '80px', textAlign: 'right',
                }}>
                  {formatAmount(nutrient.amount, nutrient.unit)}
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* ── Footnote ── */}
      <div style={{
        marginTop: '20px',
        paddingTop: '16px',
        borderTop: '1px solid #f1f5f9',
      }}>
        <p style={{
          margin: 0, fontSize: '10px', color: '#94a3b8',
          fontStyle: 'italic', lineHeight: 1.6,
        }}>
          * Values are rounded for clarity. Nutritional data is obtained from multiple verified sources.
        </p>
      </div>
    </div>
  );
};

export default NutritionLabel;