import React from 'react';
import { type MultipleNutritionResponse, type NutritionData } from '../utils/api';
import { type AlertOptions } from './PremiumAlert';

interface NutritionLabelProps {
  data: NutritionData | MultipleNutritionResponse;
  showAlert: (options: AlertOptions) => void;
}

const NUTRIENT_META: Record<string, { color: string; bg: string; border: string }> = {
  'Energy':        { color: '#c2410c', bg: '#fff7ed', border: '#fed7aa' },
  'Protein':       { color: '#0369a1', bg: '#f0f9ff', border: '#bae6fd' },
  'Total lipid':   { color: '#a16207', bg: '#fefce8', border: '#fde68a' },
  'Carbohydrate':  { color: '#15803d', bg: '#f0fdf4', border: '#bbf7d0' },
  'Fiber':         { color: '#15803d', bg: '#f0fdf4', border: '#bbf7d0' },
  'Sugars':        { color: '#be185d', bg: '#fdf2f8', border: '#fbcfe8' },
  'Fatty acids':   { color: '#b45309', bg: '#fffbeb', border: '#fde68a' },
  'Cholesterol':   { color: '#7c3aed', bg: '#faf5ff', border: '#ddd6fe' },
  'Sodium':        { color: '#0e7490', bg: '#ecfeff', border: '#a5f3fc' },
  'Calcium':       { color: '#6d28d9', bg: '#faf5ff', border: '#ddd6fe' },
  'Iron':          { color: '#b91c1c', bg: '#fef2f2', border: '#fecaca' },
  'Potassium':     { color: '#065f46', bg: '#ecfdf5', border: '#a7f3d0' },
  'Vitamin C':     { color: '#b45309', bg: '#fffbeb', border: '#fde68a' },
  'Vitamin A':     { color: '#c2410c', bg: '#fff7ed', border: '#fed7aa' },
};

const getMeta = (name: string) => {
  if (!name) return { color: '#64748b', bg: '#f8fafc', border: '#e2e8f0' };
  for (const [key, val] of Object.entries(NUTRIENT_META)) {
    if (name.includes(key)) return val;
  }
  return { color: '#64748b', bg: '#f8fafc', border: '#e2e8f0' };
};

const formatName = (name: string): string =>
  name
    .replace('Total lipid (fat)', 'Total Fat')
    .replace('Carbohydrate, by difference', 'Carbohydrate')
    .replace('Fiber, total dietary', 'Dietary Fiber')
    .replace('Sugars, total', 'Sugars')
    .replace('Fatty acids, total saturated', 'Saturated Fat')
    .replace('Vitamin C, total ascorbic acid', 'Vitamin C')
    .replace('Vitamin A, RAE', 'Vitamin A')
    .replace(/, total$/, '');

const formatAmount = (amount: number, unit: string): string => {
  const val =
    unit === 'kcal'
      ? Math.round(amount)
      : amount < 1
      ? amount.toFixed(2)
      : amount.toFixed(1);
  return `${val} ${unit === 'kcal' ? 'cal' : unit}`;
};

const NutritionLabel: React.FC<NutritionLabelProps> = ({ data, showAlert }) => {
  const isMultiple =
    'ingredients' in data && Array.isArray((data as MultipleNutritionResponse).ingredients);
  const multiData = isMultiple ? (data as MultipleNutritionResponse) : null;
  const nutrientList = isMultiple
    ? multiData!.total_nutrients ?? []
    : (data as NutritionData).nutrients ?? [];

  const calories = nutrientList.find(n => n.name && n.name.includes('Energy'));

  const getTitle = () => {
    if (!isMultiple) return (data as NutritionData).ingredient || 'Item';
    const names = multiData?.ingredients?.map(ing => ing.ingredient) || [];
    if (names.length === 0) return 'Recipe Totals';
    if (names.length === 1) return names[0];
    if (names.length === 2) return `${names[0]} & ${names[1]}`;
    if (names.length === 3) return `${names[0]}, ${names[1]} & ${names[2]}`;
    return `${names[0]}, ${names[1]} & ${names.length - 2} more`;
  };

  const copyToClipboard = () => {
    const header = isMultiple
      ? `Recipe Profile (Per 100g)`
      : `Nutrition Facts: ${(data as NutritionData).ingredient || 'Item'}`;
    const weight = isMultiple
      ? `Total Weight: ${multiData?.total_weight_g}g`
      : `Serving Size: ${(data as NutritionData).quantity_g}g`;
    const lines = nutrientList.map(n => `${n.name}: ${n.amount}${n.unit}`);
    const text = `${header}\n${weight}\n\n${lines.join('\n')}\n\nGenerated by Nutritive`;

    navigator.clipboard.writeText(text).then(() => {
      showAlert({ type: 'success', message: 'Nutritional facts copied to clipboard!' });
    }).catch(err => {
      console.error('Failed to copy text: ', err);
      showAlert({ type: 'error', message: 'Failed to copy to clipboard.' });
    });
  };

  const visibleNutrients = nutrientList.filter(n => n.name && !n.name.includes('Energy'));

  return (
    <div style={{ width: '100%', boxSizing: 'border-box', fontFamily: "'DM Sans', 'Outfit', ui-sans-serif, system-ui, sans-serif" }}>

      {/* ── Header ──────────────────────────────────────────── */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '24px',
        gap: '16px',
      }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          {/* Eyebrow */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '7px', marginBottom: '8px' }}>
            <div style={{ width: '3px', height: '13px', background: 'linear-gradient(180deg, #10b981, #059669)', borderRadius: '4px' }} />
            <p style={{
              margin: 0, fontSize: '10px', fontWeight: '800',
              color: '#94a3b8', letterSpacing: '0.1em', textTransform: 'uppercase',
            }}>
              {isMultiple ? 'Recipe Analysis' : 'Food Analysis'}
            </p>
          </div>

          {/* Title */}
          <h2 style={{
            margin: '0 0 10px',
            fontSize: '26px',
            fontWeight: '800',
            color: '#0f172a',
            textTransform: 'capitalize',
            letterSpacing: '-0.02em',
            lineHeight: 1.2,
          }}>
            {getTitle()}
          </h2>

          {/* Serving badge */}
          <div style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
            <span style={{
              fontSize: '11px', fontWeight: '700', color: '#059669',
              background: '#f0fdf9', padding: '3px 10px',
              borderRadius: '100px', border: '1px solid #a7f3d0',
              letterSpacing: '0.03em', textTransform: 'uppercase',
            }}>
              Nutrition Facts
            </span>
            <span style={{ fontSize: '12px', fontWeight: '500', color: '#94a3b8' }}>
              {isMultiple ? 'Per 100g' : `${(data as NutritionData).quantity_g}g serving`}
            </span>
            {isMultiple && (
              <span style={{
                fontSize: '10px', fontWeight: '700', color: '#0369a1',
                background: '#f0f9ff', padding: '3px 9px',
                borderRadius: '100px', border: '1px solid #bae6fd',
                letterSpacing: '0.03em',
              }}>
                ⚖ Weighted
              </span>
            )}
          </div>
        </div>

        {/* Copy button */}
        <button
          onClick={copyToClipboard}
          style={{
            padding: '9px 16px',
            borderRadius: '12px',
            background: '#f8fafc',
            border: '1.5px solid #e2e8f0',
            cursor: 'pointer',
            fontSize: '12px',
            fontWeight: '700',
            color: '#64748b',
            transition: 'all 0.2s ease',
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
            whiteSpace: 'nowrap',
            flexShrink: 0,
            fontFamily: 'inherit',
          }}
          onMouseEnter={e => {
            e.currentTarget.style.background = '#f0fdf9';
            e.currentTarget.style.borderColor = '#a7f3d0';
            e.currentTarget.style.color = '#059669';
          }}
          onMouseLeave={e => {
            e.currentTarget.style.background = '#f8fafc';
            e.currentTarget.style.borderColor = '#e2e8f0';
            e.currentTarget.style.color = '#64748b';
          }}
        >
          <svg width="13" height="13" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
            <rect x="5" y="5" width="9" height="9" rx="2" />
            <path d="M3 11V3a2 2 0 012-2h8" />
          </svg>
          Copy
        </button>
      </div>

      {/* ── Calories hero ────────────────────────────────────── */}
      {calories && (
        <div style={{
          background: 'linear-gradient(135deg, #f0fdf9 0%, #ecfdf5 100%)',
          border: '1.5px solid #a7f3d0',
          borderRadius: '20px',
          padding: '20px 24px',
          marginBottom: '24px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          gap: '16px',
        }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '7px', marginBottom: '3px' }}>
              <svg width="16" height="16" viewBox="0 0 20 20" fill="none">
                <path d="M10 2C6 6 4 9 4 12a6 6 0 0012 0c0-3-2-6-6-10z" fill="#f97316" opacity="0.85" />
              </svg>
              <p style={{ margin: 0, fontSize: '11px', fontWeight: '800', color: '#065f46', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
                Energy Content
              </p>
            </div>
            <p style={{ margin: 0, fontSize: '13px', color: '#6b7280', fontWeight: '500' }}>
              Estimated {isMultiple ? 'per 100g' : 'per serving'}
            </p>
          </div>

          <div style={{ textAlign: 'right', flexShrink: 0 }}>
            <p style={{ margin: 0, fontSize: '48px', fontWeight: '900', color: '#0f172a', lineHeight: 1, letterSpacing: '-0.03em' }}>
              {Math.round(calories.amount)}
            </p>
            <p style={{ margin: 0, fontSize: '11px', fontWeight: '700', color: '#6b7280', textTransform: 'uppercase', letterSpacing: '0.08em', marginTop: '2px' }}>
              Calories
            </p>
          </div>
        </div>
      )}

      {/* ── Nutrient list ────────────────────────────────────── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>

        {/* Column headers */}
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          padding: '0 6px 10px',
          borderBottom: '1.5px solid #f1f5f9',
          marginBottom: '10px',
        }}>
          <span style={{ fontSize: '10px', fontWeight: '800', color: '#cbd5e1', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
            Nutrient
          </span>
          <span style={{ fontSize: '10px', fontWeight: '800', color: '#cbd5e1', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
            Amount
          </span>
        </div>

        {/* Rows */}
        {visibleNutrients.map((nutrient, index) => {
          const meta = getMeta(nutrient.name);
          return (
            <div
              key={index}
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                padding: '12px 16px',
                borderRadius: '14px',
                backgroundColor: '#ffffff',
                border: '1px solid #f1f5f9',
                marginBottom: '6px',
                transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
                cursor: 'default',
              }}
              onMouseEnter={e => {
                e.currentTarget.style.background = meta.bg;
                e.currentTarget.style.borderColor = meta.border;
                e.currentTarget.style.transform = 'translateX(3px)';
                e.currentTarget.style.boxShadow = `0 2px 12px rgba(0,0,0,0.05)`;
              }}
              onMouseLeave={e => {
                e.currentTarget.style.background = '#ffffff';
                e.currentTarget.style.borderColor = '#f1f5f9';
                e.currentTarget.style.transform = 'translateX(0)';
                e.currentTarget.style.boxShadow = 'none';
              }}
            >
              {/* Name */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <div style={{
                  width: '7px', height: '7px', borderRadius: '50%',
                  background: meta.color, flexShrink: 0,
                  boxShadow: `0 0 0 2px ${meta.bg}`,
                }} />
                <span style={{ fontSize: '14px', fontWeight: '600', color: '#334155', letterSpacing: '-0.01em' }}>
                  {formatName(nutrient.name)}
                </span>
              </div>

              {/* Amount */}
              <span style={{
                fontSize: '14px',
                fontWeight: '700',
                color: '#1e293b',
                background: meta.bg,
                padding: '3px 10px',
                borderRadius: '8px',
                border: `1px solid ${meta.border}`,
                letterSpacing: '-0.01em',
                flexShrink: 0,
              }}>
                {formatAmount(nutrient.amount, nutrient.unit)}
              </span>
            </div>
          );
        })}
      </div>

      {/* ── Footnote ─────────────────────────────────────────── */}
      <div style={{ marginTop: '16px', paddingTop: '14px', borderTop: '1px solid #f1f5f9' }}>
        <p style={{ margin: 0, fontSize: '10px', color: '#94a3b8', lineHeight: 1.7, letterSpacing: '0.01em' }}>
          * Values are rounded for clarity. Nutritional data is obtained from multiple verified sources.
        </p>
      </div>
    </div>
  );
};

export default NutritionLabel;