import React from 'react';
import { type MultipleNutritionResponse, type NutritionData } from '../utils/api';
import { type AlertOptions } from './PremiumAlert';

interface NutritionLabelProps {
  data: NutritionData | MultipleNutritionResponse;
  showAlert: (options: AlertOptions) => void;
}

const NUTRIENT_META: Record<string, { color: string; bg: string; icon: string }> = {
  'Energy':        { color: '#ea580c', bg: '#fff7ed', icon: '🔥' },
  'Protein':       { color: '#0284c7', bg: '#f0f9ff', icon: '💪' },
  'Total lipid':   { color: '#ca8a04', bg: '#fefce8', icon: '🫙' },
  'Carbohydrate':  { color: '#16a34a', bg: '#f0fdf4', icon: '🌾' },
  'Fiber':         { color: '#15803d', bg: '#f0fdf4', icon: '🌿' },
  'Sugars':        { color: '#db2777', bg: '#fdf2f8', icon: '🍬' },
  'Fatty acids':   { color: '#b45309', bg: '#fffbeb', icon: '🧈' },
  'Cholesterol':   { color: '#9333ea', bg: '#faf5ff', icon: '❤️' },
  'Sodium':        { color: '#0891b2', bg: '#ecfeff', icon: '🧂' },
  'Calcium':       { color: '#7c3aed', bg: '#faf5ff', icon: '🦴' },
  'Iron':          { color: '#b91c1c', bg: '#fef2f2', icon: '⚙️' },
  'Potassium':     { color: '#065f46', bg: '#ecfdf5', icon: '🍌' },
  'Vitamin C':     { color: '#d97706', bg: '#fffbeb', icon: '🍊' },
  'Vitamin A':     { color: '#c2410c', bg: '#fff7ed', icon: '🥕' },
};

const getMeta = (name: string) => {
  if (!name) return { color: '#475569', bg: '#f8fafc', icon: '•' };
  for (const [key, val] of Object.entries(NUTRIENT_META)) {
    if (name.includes(key)) return val;
  }
  return { color: '#475569', bg: '#f8fafc', icon: '•' };
};

const formatName = (name: string): string =>
  name
    .replace('Total lipid (fat)', 'Total Fat')
    .replace('Carbohydrate, by difference', 'Carbohydrate')
    .replace('Fiber, total dietary', 'Dietary Fiber')
    .replace('Sugars, total', 'Sugars')
    .replace('Fatty acids, total saturated', 'Saturated Fat')
    .replace('Vitamin C, total ascorbic acid', 'Vitamin C')
    .replace('Vitamin A, RAE', 'Vitamin A')
    .replace(/, total$/, '');

const formatAmount = (amount: number, unit: string): string => {
  const val =
    unit === 'kcal'
      ? Math.round(amount)
      : amount < 1
      ? amount.toFixed(2)
      : amount.toFixed(1);
  return `${val} ${unit === 'kcal' ? 'cal' : unit}`;
};

const DV_LIMITS: Record<string, number> = {
  'Energy': 2000, 'Protein': 50, 'Total lipid': 78,
  'Carbohydrate': 275, 'Fiber': 28, 'Sugars': 50,
  'Fatty acids': 20, 'Cholesterol': 300, 'Sodium': 2300,
  'Calcium': 1300, 'Iron': 18, 'Potassium': 4700,
  'Vitamin C': 90, 'Vitamin A': 900,
};

const calculateDV = (name: string, amount: number): number | null => {
  if (!name) return null;
  for (const [key, dv] of Object.entries(DV_LIMITS)) {
    if (name.includes(key)) return Math.min(100, Math.round((amount / dv) * 100));
  }
  return null;
};

const NutritionLabel: React.FC<NutritionLabelProps> = ({ data, showAlert }) => {
  const isMultiple =
    'ingredients' in data && Array.isArray((data as MultipleNutritionResponse).ingredients);
  const multiData = isMultiple ? (data as MultipleNutritionResponse) : null;
  const nutrientList = isMultiple
    ? multiData!.total_nutrients ?? []
    : (data as NutritionData).nutrients ?? [];

  const calories = nutrientList.find(n => n.name && n.name.includes('Energy'));

  const getTitle = () => {
    if (!isMultiple) return (data as NutritionData).ingredient || 'Item';
    const names = multiData?.ingredients?.map(ing => ing.ingredient) || [];
    if (names.length === 0) return 'Recipe Totals';
    if (names.length === 1) return names[0];
    if (names.length === 2) return `${names[0]} & ${names[1]}`;
    if (names.length === 3) return `${names[0]}, ${names[1]} & ${names[2]}`;
    return `${names[0]}, ${names[1]} & ${names.length - 2} more`;
  };

  const copyToClipboard = () => {
    const header = isMultiple ? `Recipe Profile (Per 100g)` : `Nutrition Facts: ${(data as NutritionData).ingredient || 'Item'}`;
    const weight = isMultiple ? `Total Weight: ${multiData?.total_weight_g}g` : `Serving Size: ${(data as NutritionData).quantity_g}g`;
    const lines = nutrientList.map(n => `${n.name}: ${n.amount}${n.unit}`);
    const text = `${header}\n${weight}\n\n${lines.join('\n')}\n\nGenerated by Nutritional Label Generator`;

    navigator.clipboard.writeText(text).then(() => {
      showAlert({ type: 'success', message: 'Nutritional facts copied to clipboard!' });
    }).catch(err => {
      console.error('Failed to copy text: ', err);
      showAlert({ type: 'error', message: 'Failed to copy to clipboard.' });
    });
  };

  const visibleNutrients = nutrientList.filter(n => n.name && !n.name.includes('Energy'));

  return (
    <div style={{ width: '100%', boxSizing: 'border-box' }}>

      {/* ── Top header bar ── */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '24px',
        gap: '12px',
      }}>
        <div>
          {/* eyebrow */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
            <div style={{ width: '4px', height: '14px', background: '#14b8a6', borderRadius: '4px' }} />
            <p style={{
              margin: 0, fontSize: '11px', fontWeight: '800',
              color: '#94a3b8', letterSpacing: '0.1em', textTransform: 'uppercase',
            }}>
              {isMultiple ? 'Recipe Analysis' : 'Food Analysis'}
            </p>
          </div>
          <h2 style={{ 
            margin: '0 0 4px', 
            fontSize: '24px', 
            fontWeight: '900', 
            color: '#0f172a',
            textTransform: 'capitalize'
          }}>
            {getTitle()}
          </h2>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <span style={{
              fontSize: '11px',
              fontWeight: '800',
              color: '#14b8a6',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              background: '#f0fdfa',
              padding: '2px 8px',
              borderRadius: '6px',
              border: '1px solid #ccfbf1'
            }}>
              Nutrition Facts
            </span>
            <span style={{ fontSize: '13px', fontWeight: '600', color: '#64748b' }}>
              • {isMultiple ? 'Normalized per 100g' : `${(data as NutritionData).quantity_g}g serving`}
            </span>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }}>
          {isMultiple && (
            <div style={{
              background: '#f0fdf4', color: '#16a34a',
              padding: '5px 10px', borderRadius: '10px',
              fontSize: '10px', fontWeight: '800',
              border: '1px solid #dcfce7', whiteSpace: 'nowrap',
              letterSpacing: '0.04em',
            }}>
              ⚖️ WEIGHTED
            </div>
          )}
          <button
            onClick={copyToClipboard}
            style={{
              padding: '8px 14px', borderRadius: '12px',
              background: '#f8fafc', border: '1px solid #e2e8f0',
              cursor: 'pointer', fontSize: '12px', fontWeight: '700',
              color: '#64748b', transition: 'all 0.2s',
              display: 'flex', alignItems: 'center', gap: '5px',
              whiteSpace: 'nowrap',
            }}
            onMouseEnter={e => {
              e.currentTarget.style.background = '#f0fdfa';
              e.currentTarget.style.borderColor = '#ccfbf1';
              e.currentTarget.style.color = '#0d9488';
            }}
            onMouseLeave={e => {
              e.currentTarget.style.background = '#f8fafc';
              e.currentTarget.style.borderColor = '#e2e8f0';
              e.currentTarget.style.color = '#64748b';
            }}
          >
            📋 Copy
          </button>
        </div>
      </div>

      {/* ── Calories hero block ── */}
      {calories && (
        <div style={{
          background: 'linear-gradient(135deg, #f0fdfa, #f0f9ff)',
          border: '1.5px solid #ccfbf1',
          borderRadius: '20px',
          padding: '20px 24px',
          marginBottom: '24px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          gap: '16px',
        }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '2px' }}>
              <span style={{ fontSize: '16px' }}>🔥</span>
              <p style={{ margin: 0, fontSize: '12px', fontWeight: '800', color: '#0d9488', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                Calories
              </p>
            </div>
            <p style={{ margin: 0, fontSize: '12px', color: '#64748b', fontWeight: '500' }}>
              {isMultiple ? 'Per 100g' : 'Per serving'}
            </p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{ margin: 0, fontSize: '48px', fontWeight: '900', color: '#0f172a', lineHeight: 1 }}>
              {Math.round(calories.amount)}
            </p>
            <p style={{ margin: 0, fontSize: '11px', fontWeight: '700', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              kcal
            </p>
          </div>
        </div>
      )}

      {/* ── Nutrient list ── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
        {/* Column headers */}
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          padding: '0 4px 10px',
          borderBottom: '2px solid #f1f5f9',
          marginBottom: '6px',
        }}>
          <span style={{ fontSize: '11px', fontWeight: '800', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
            Nutrient
          </span>
          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            <span style={{ fontSize: '11px', fontWeight: '800', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.08em', minWidth: '80px', textAlign: 'right' }}>
              Amount
            </span>
            <span style={{ fontSize: '11px', fontWeight: '800', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.08em', minWidth: '44px', textAlign: 'right' }}>
              % DV
            </span>
          </div>
        </div>

        {visibleNutrients.map((nutrient, index) => {
          const meta = getMeta(nutrient.name);
          const dv = calculateDV(nutrient.name, nutrient.amount);
          const isLast = index === visibleNutrients.length - 1;

          return (
            <div
              key={index}
              style={{
                padding: '10px 4px',
                borderBottom: isLast ? 'none' : '1px solid #f8fafc',
              }}
            >
              {/* Row */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: dv !== null ? '8px' : '0' }}>
                {/* Left: icon + name */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <div style={{
                    width: '30px', height: '30px', borderRadius: '9px',
                    background: meta.bg,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: '14px', flexShrink: 0,
                    border: `1px solid ${meta.color}18`,
                  }}>
                    {meta.icon}
                  </div>
                  <span style={{ fontSize: '14px', fontWeight: '600', color: '#1e293b' }}>
                    {formatName(nutrient.name)}
                  </span>
                </div>

                {/* Right: amount + DV% */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{
                    fontSize: '14px', fontWeight: '800', color: meta.color,
                    minWidth: '80px', textAlign: 'right',
                  }}>
                    {formatAmount(nutrient.amount, nutrient.unit)}
                  </span>
                  <span style={{
                    fontSize: '12px', fontWeight: '800',
                    color: dv !== null ? '#475569' : '#cbd5e1',
                    minWidth: '44px', textAlign: 'right',
                  }}>
                    {dv !== null ? `${dv}%` : '—'}
                  </span>
                </div>
              </div>

              {/* Progress bar */}
              {dv !== null && (
                <div style={{
                  marginLeft: '40px',
                  height: '5px',
                  background: '#f1f5f9',
                  borderRadius: '99px',
                  overflow: 'hidden',
                }}>
                  <div style={{
                    width: `${dv}%`,
                    height: '100%',
                    background: meta.color,
                    borderRadius: '99px',
                    transition: 'width 1s ease-out',
                    opacity: 0.85,
                  }} />
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* ── Footnote ── */}
      <div style={{
        marginTop: '20px',
        paddingTop: '16px',
        borderTop: '1px solid #f1f5f9',
      }}>
        <p style={{
          margin: 0, fontSize: '10px', color: '#94a3b8',
          fontStyle: 'italic', lineHeight: 1.6,
        }}>
          * The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice.
        </p>
      </div>
    </div>
  );
};

export default NutritionLabel;